import { Button, VerticalBox, LineEdit, ListView } from "std-widgets.slint";

export AppWindow := Window {
    preferred-width: 800px;
    preferred-height: 600px;
    property<[string]> all_objects: [
        "Tower", "Candle", "Car", "Airplane"
    ];
    property<[string]> objects: all_objects;
    callback update-filter(string);
    VerticalBox { 
        filter-edit := LineEdit {
            placeholder-text: "Enter text to filter and press enter to activate.";
            accepted => { root.update-filter(self.text); }
        }
        ListView {
            for name in objects: Text {
                text: name;
                Rectangle {
                    border-width: 1px;
                    border-color: black;
                }
            }
        }
     }
}
